# Generated by Django 4.0 on 2022-01-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('load_date', models.DateField()),
                ('ac_advisor', models.CharField(max_length=40)),
                ('originality', models.IntegerField(default=0)),
            ],
        ),
    ]
