# Generated by Django 4.0 on 2022-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houston', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='load_date',
            field=models.DateField(auto_created='2022-01-23'),
        ),
    ]
