# Generated by Django 4.0 on 2022-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houston', '0002_alter_portfolio_load_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='load_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
